version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.prod
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/db:/docker-entrypoint-initdb.d
      - ./logs/pg-log:/var/pg-log
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
